# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: linux-64
channels:
  - conda-forge    # Or defaults, depending on packages
  - bioconda       # For bioinformatics tools like flexbar
  - defaults       # For general packages like pandas
dependencies:
  - biopython
  - flexbar
  - seqkit
  - pandas
